#!/bin/ksh

#------------------------------
# Print help for master_post.sh
#------------------------------
echo "The script master_post.sh allows the following options:
-h, --help                    Show this help and exit
-g GCM, --gcm GCM             Specify the driving GCM
-x EXP, --exp EXP             Specify the driving experiment name
-s START, --start START       Specify the start date for post-processing (format YYYY)
-e END, --end END             Specify the end date for post-processing (format YYYY)
-S, --silent                  Reduce log output
-V, --verbose                 Increase log output
-O, --overwrite               Overwrite existing output
-C, --create_const            Create constant vraiables
-p, --proc_list               List of variables to process; separated by spaces and in quotation marks, e.g -p 'pr tas'" 


